const PLATFORMS: { value: Platform; label: string; url: string; keyless?: boolean }[] = [
  // Original v1 platforms
  { value: 'google', label: 'Google AI Studio', url: 'https://aistudio.google.com/apikey' },
  { value: 'groq', label: 'Groq', url: 'https://console.groq.com/keys' },
  { value: 'cerebras', label: 'Cerebras', url: 'https://cloud.cerebras.ai' },
  { value: 'nvidia', label: 'NVIDIA NIM', url: 'https://build.nvidia.com/settings/api-keys' },
  { value: 'mistral', label: 'Mistral', url: 'https://console.mistral.ai/api-keys/' },
  { value: 'openrouter', label: 'OpenRouter', url: 'https://openrouter.ai/keys' },
  { value: 'github', label: 'GitHub Models', url: 'https://github.com/settings/tokens' },
  { value: 'cohere', label: 'Cohere', url: 'https://dashboard.cohere.com/api-keys' },
  { value: 'cloudflare', label: 'Cloudflare Workers AI', url: 'https://dash.cloudflare.com' },
  { value: 'zhipu', label: 'Zhipu AI (Z.ai)', url: 'https://z.ai/manage-apikey/apikey-list' },
  { value: 'ollama', label: 'Ollama Cloud', url: 'https://ollama.com/settings/keys' },
  { value: 'kilo', label: 'Kilo Gateway (no key needed)', url: 'https://app.kilo.ai', keyless: true },
  { value: 'pollinations', label: 'Pollinations (no key needed)', url: 'https://pollinations.ai', keyless: true },
  { value: 'ovh', label: 'OVH AI Endpoints (no key needed)', url: 'https://endpoints.ai.cloud.ovh.net', keyless: true },
  { value: 'llm7', label: 'LLM7 (anon ok)', url: 'https://llm7.io' },
  { value: 'huggingface', label: 'HuggingFace Router', url: 'https://huggingface.co/settings/tokens' },
  { value: 'opencode', label: 'OpenCode Zen (free key)', url: 'https://opencode.ai/auth' },
  { value: 'agnes', label: 'Agnes AI (free key)', url: 'https://platform.agnes-ai.com' },
  { value: 'reka', label: 'Reka (free key)', url: 'https://platform.reka.ai' },
  { value: 'siliconflow', label: 'SiliconFlow (image + TTS)', url: 'https://siliconflow.com' },
  // Yangmao-supplemented platforms (no duplicates, no local-only)
  { value: 'aimlapi', label: 'AI/ML API', url: 'https://aimlapi.com/app/api-keys' },
  { value: 'ai21-labs', label: 'AI21 Labs', url: 'https://studio.ai21.com/account/api-keys' },
  { value: 'anyscale', label: 'Anyscale', url: 'https://app.endpoints.anyscale.com/credentials' },
  { value: 'awanllm', label: 'AwanLLM', url: 'https://awanllm.com' },
  { value: 'baichuan', label: 'Baichuan AI', url: 'https://platform.baichuan-ai.com/api-key' },
  { value: 'clawbrain', label: 'ClawBrain', url: 'https://www.clawbrain.dev' },
  { value: 'deepinfra', label: 'DeepInfra', url: 'https://deepinfra.com/dash/api_keys' },
  { value: 'deepseek', label: 'DeepSeek', url: 'https://platform.deepseek.com/api_keys' },
  { value: 'doubao', label: 'Doubao (ByteDance)', url: 'https://console.volcengine.com/ark/api-key' },
  { value: 'ernie', label: 'ERNIE Bot (Baidu)', url: 'https://console.bce.baidu.com/ai/#/ai/wenxinworkshop/app/list' },
  { value: 'fireworks', label: 'Fireworks AI', url: 'https://fireworks.ai/api-keys' },
  { value: 'grok', label: 'Grok (xAI)', url: 'https://console.x.ai' },
  { value: 'kimi', label: 'Kimi (Moonshot AI)', url: 'https://kimi.moonshot.cn' },
  { value: 'lepton', label: 'Lepton AI', url: 'https://lepton.ai/dashboard/api-keys' },
  { value: 'minimax', label: 'MiniMax', url: 'https://platform.minimaxi.com/api-keys' },
  { value: 'monsterapi', label: 'MonsterAPI', url: 'https://monsterapi.ai' },
  { value: 'nebius', label: 'Nebius AI Studio', url: 'https://studio.nebius.com/settings/api-keys' },
  { value: 'novita', label: 'Novita AI', url: 'https://novita.ai/settings/api-keys' },
  { value: 'octoai', label: 'OctoAI', url: 'https://octo.ai/api-keys' },
  { value: 'openpipe', label: 'OpenPipe', url: 'https://openpipe.ai/settings/api-keys' },
  { value: 'parasail', label: 'Parasail', url: 'https://parasail.io' },
  { value: 'portkey-ai', label: 'Portkey AI', url: 'https://app.portkey.ai/api-keys' },
  { value: 'qwen', label: 'Qwen (Alibaba Cloud)', url: 'https://dashscope.aliyun.com/api-key' },
  { value: 'runpod', label: 'RunPod', url: 'https://www.runpod.io/console/user/settings' },
  { value: 'sambanova', label: 'SambaNova', url: 'https://cloud.sambanova.ai/account/api-keys' },
  { value: 'stepfun', label: 'StepFun (StepStar)', url: 'https://platform.stepfun.com/api-key' },
  { value: 'together-ai', label: 'Together AI', url: 'https://api.together.ai/settings/api-keys' },
]